spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=True&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://47.103.203.182:3306/blog?useUnicode=True&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: info
    com.adam: debug
  file: log/blog-dev.log